export default defineAppConfig({
  title: 'Shaf',
  documentation: 'https://docs.sink.cool',
  github: 'https://github.com/miantiao-me/sink',
  coffee: 'https://sink.cool/coffee',
  twitter: 'https://sink.cool/x',
  telegram: 'https://sink.cool/telegram',
  description: 'A Simple / Speedy / Secure Link Shortener with Analytics, 100% run on Cloudflare.',
  image: 'https://sink.cool/banner.png',
  previewTTL: 300, // 5 minutes
  slugRegex: /^[a-z0-9]+(?:-[a-z0-9]+)*$/i,
  reserveSlug: [
    // 1. Web Standards, Security & Browser Files
    '.well-known',
    'robots.txt',
    'sitemap.xml',
    'sitemap',
    'security.txt',
    'humans.txt',
    'ads.txt',
    'manifest.json',
    'manifest.webmanifest',
    'favicon.ico',
    'favicon.png',
    'apple-touch-icon.png',
    'apple-touch-icon-precomposed.png',
    'icon.png',
    'sphere.bin', // Sink 3D Globe asset
    'sw.js',

    // 2. Framework & Internal Assets (Nuxt & Nitro)
    '_nuxt',
    '_nitro',
    '_assets',
    '__nuxt_error',
    'assets',
    'public',

    // 3. Application, Auth & Onboarding
    'dashboard',
    'app',
    'admin',
    'root',
    'auth',
    'login',
    'register',
    'signup',
    'signin',
    'logout',
    'signout',
    'onboarding',
    'callback',
    'verify',
    'oauth',
    'sso',
    'forgot-password',
    'reset-password',

    // 4. Multi-Tenant Workspace & Team Operations
    'workspace',
    'workspaces',
    'account',
    'settings',
    'profile',
    'team',
    'members',
    'invite',
    'invites',
    'domains',

    // 5. Billing, Subscriptions & Dev Infrastructure
    'billing',
    'checkout',
    'portal',
    'invoices',
    'upgrade',
    'pricing',
    'api',
    'webhooks',
    'analytics',
    'stats',
    'logs',
    'inspect',

    // 6. Marketing & Public Pages
    'features',
    'about',
    'contact',
    'terms',
    'privacy',
    'legal',
    'security',
    'blog',
    'docs',
    '_docs',
    'faq',
    'status',
    'help',
    'support',
    'changelog',
    'roadmap',
    'integrations',
    'affiliates',
    'partners',
    'careers',

    // 7. Free Public Tools
    'tools',
    'qr',
    'utm',
    'utm-builder',

    // 8. Reserved Operations & Edge Keywords
    'new',
    'edit',
    'delete',
    'create',
    'download',
    'view',
    'proxy',
    'cloaked',
    'health',
    'ping',
    'null',
    'undefined',
    'true',
    'false',
  ],
})
